edugame/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('game/', include('game.urls')),
    path('users/', include('users.urls')),
    path('', include('home.urls')),
    path('accounts/', include('allauth.urls')),
]

game/urls.py
from django.urls import path, include
from . import views

app_name = 'game'

urlpatterns = [
    path('start/', views.start_game, name='start_game'),
    path('load/<int:game_id>/', views.load_game, name='load_game'),
    path('generate/<int:game_id>/', views.generate_questions, name='generate_questions'),
    path('play/<int:game_id>/', views.play_game, name='play_game'),
    path('end/<int:game_id>/', views.end_game, name='end_game'),
    path('list/', views.list_game, name="list"),
    path('delete/', views.delete_game, name="delete"),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index')
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'home/index.html')

home/templates/home/index.html
{% extends 'base.html' %}
{% block body %}
<section id="intro" class="mt-8 flex flex-col items-center justify-center p-6 mb-12">
    <h2 class="max-w-4xl text-4xl font-bold text-center text-slate-900">
        AI Supported <span class="text-purple-600">Education</span> Advisor
    </h2>
    <p class="max-w-md text-2xl mt-4 text-center text-slate-700">Smart Problem Roulette that supports <span class="italic text-purple-600">ANY</span> subject. </p>
    <p class="max-w-md text-lg mt-2 text-center text-slate-700">Boost your learning with personalized, AI-generated questions and track your progress with insightful statistics!</p>
</section>

<div class="flex justify-center space-x-8">
    <a href="{% url 'game:list' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-3 px-6 rounded-md shadow-md transition duration-300">
        <h1 class="text-xl">Load Game</h1>
    </a>
    <a href="{% url 'game:start_game' %}" class="bg-green-500 hover:bg-green-700 text-white font-bold py-3 px-6 rounded-md shadow-md transition duration-300">
        <h1 class="text-xl">Start Game</h1>
    </a>
</div>

{% endblock body %}