edugame/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('game/', include('game.urls')),
    path('users/', include('users.urls')),
    path('', include('home.urls')),
    path('accounts/', include('allauth.urls')),
]

game/urls.py
from django.urls import path, include
from . import views

app_name = 'game'

urlpatterns = [
    path('start/', views.start_game, name='start_game'),
    path('load/<int:game_id>/', views.load_game, name='load_game'),
    path('generate/<int:game_id>/', views.generate_questions, name='generate_questions'),
    path('play/<int:game_id>/', views.play_game, name='play_game'),
    path('end/<int:game_id>/', views.end_game, name='end_game'),
    path('list/', views.list_game, name="list"),
    path('delete/', views.delete_game, name="delete"),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('save_achievement/', views.save_achievement, name="save_achievement"),
    path('delete_achievement/', views.delete_achievement, name='delete_achievement'),
    path('friends/', views.list_friends, name="friends"),
    path('friends/add/<int:user_id>/', views.send_friend_request, name="friend_request"),
    path('friends/requests/', views.list_received_request, name="received_friend_request"),
    path('friends/accept/<int:requestID>/', views.accept_friend_request, name="accept_friend_request"),
    path('friends/reject/<int:requestID>/', views.reject_friend_request, name="reject_friend_request"),
    path('friends/remove/<int:friendID>/', views.remove_friend, name="remove_friend"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    friends = models.ManyToManyField('User', blank=True)

class Friend_Request(models.Model):
    from_user = models.ForeignKey(User, related_name="from_user", on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, related_name="to_user", on_delete=models.CASCADE)


class Achievement(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=300, default="")
    date_created = models.DateTimeField(auto_now_add=True)

class Profile(models.Model):
    # add user
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=1)
    games_completed = models.IntegerField(default=0)
    subjects_completed = models.JSONField(default=dict, blank=True)
    
    def __str__(self):
        return self.user.username
    

users/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.decorators import login_required
from allauth.socialaccount.models import SocialAccount
from gemini.functions import gemini_generate_achievement
from .models import Achievement, Profile, Friend_Request
from django.contrib.auth import get_user_model
import json

User = get_user_model()

# Create your views here.


@login_required
def profile(request, user_id):
    user = User.objects.get(pk=user_id)
    profile = Profile.objects.get(user=user)
    achievements = Achievement.objects.filter(user=user)
    return render(request, 'users/profile.html', {'profile': profile, 'achievements': achievements, "profile_user": user})

@login_required
def save_achievement(request):
    if request.method == "POST":
        user = request.user
        achievement = Achievement()
        data = json.loads(request.body)
        achievement.name = data['name']
        achievement.description = data['description']
        achievement.user = user
        achievement.save()
        return JsonResponse({"message": "successfully saved achievement"}, status=200)
    else:
        return JsonResponse({"message": "Invalid Request Method"}, status=400)
    

@login_required
def delete_achievement(request):
    if request.method == 'POST':
        achievement_id = request.GET.get('achievement_id')
        try:
            achievement = Achievement.objects.get(pk=achievement_id)
            achievement.delete()
            return JsonResponse({'success': True})
        except Achievement.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Achievement not found.'})
    else:
        return JsonResponse({'success': False, 'error': 'Invalid request method.'})
    


@login_required
def list_friends(request):
    friends = request.user.friends.all()
    return render(request, 'users/friends.html', {'friends': friends})

@login_required
def send_friend_request(request, user_id):
    from_user = request.user
    to_user = User.objects.get(id=user_id)
    if from_user == to_user:
        return HttpResponse('You cannot send a friend request to yourself.') 
    if to_user in from_user.friends.all():
        return HttpResponse('You are already friends with this user.' )
    friend_request, created = Friend_Request.objects.get_or_create(from_user=from_user, to_user=to_user)
    if created:
        return HttpResponse('Friend request sent!')
    else:
        return HttpResponse('Friend request already sent!')
    
@login_required
def list_received_request(request):
    currentUser = request.user
    received_requests = Friend_Request.objects.filter(to_user=currentUser)
    return render(request,'users/friend_requests.html', {'friendrequests': received_requests})

@login_required
def accept_friend_request(request, requestID):
    friend_request = Friend_Request.objects.get(id=requestID)
    if friend_request.to_user == request.user:
        friend_request.to_user.friends.add(friend_request.from_user)
        friend_request.from_user.friends.add(friend_request.to_user)
        friend_request.delete()
        return HttpResponse('friend request accepted')
    else:
        return HttpResponse('Invalid Request')

@login_required
def reject_friend_request(request, requestID):
    if request.method == 'POST':
        try:
            friend_request = Friend_Request.objects.get(id=requestID)
            friend_request.delete()
            return JsonResponse({'success': True})
        except Friend_Request.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Friend request not found.'})
    else:
        return JsonResponse({'success': False, 'error': 'Invalid request method.'})
    
@login_required
def remove_friend(request, friendID):
    if request.method == 'POST':
        try:
            friend = User.objects.get(id=friendID)
            request.user.friends.remove(friend)  # Remove friend from current user's list
            friend.friends.remove(request.user)  # Remove current user from friend's list
            return JsonResponse({'success': True})
        except User.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Friend not found.'})
    else:
        return JsonResponse({'success': False, 'error': 'Invalid request method.'})

users/templates/users/friend_requests.html
{% extends 'base.html' %}
{% block body %}
<div class="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
    <h1 class="text-3xl font-bold text-gray-800 mb-4">Friend Requests</h1>

    <div class="w-full md:w-1/2">
        {% if friendrequests %}

        <ul class="bg-white rounded-md shadow-md divide-y divide-gray-200">
            {% for friendrequest in friendrequests %}
                <li class="px-6 py-4 flex items-center justify-between" id="request-{{ friendrequest.id }}"> 
                    <div class="flex items-center">
                        <!-- Add a profile picture placeholder here if you have one -->
                        <div class="ml-4">
                            <p class="text-lg font-medium text-gray-800">
                                From: {{ friendrequest.from_user.username }}
                            </p>
                            <!-- Add other details about the request if needed -->
                        </div>
                    </div>
                    <div class="space-x-2">
                        <button class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" 
                                onclick="acceptFriendRequest({{ friendrequest.id }})">
                            Accept
                        </button>
                        <button class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" 
                                onclick="rejectFriendRequest({{ friendrequest.id }})">
                            Reject
                        </button>
                    </div>
                </li>
            {% endfor %}
        </ul>
        {% else %}
        <div class="bg-white rounded-md shadow-md p-6 text-center">
            <p class="text-gray-700">You don't have any friend requests currently.</p>
        </div>
        {% endif %}
    </div>
</div>
{% endblock body %}

{% block script %}
<script>
    async function acceptFriendRequest(requestID) {
        if (confirm("Are you sure you want to accept this friend request?")) {
            const endpointURL = `{% url 'users:accept_friend_request' requestID=99999 %}`.replace('99999', requestID);

            try {
                const response = await fetch(endpointURL, {
                    method: "POST",
                    headers: {
                        "X-CSRFToken": "{{ csrf_token }}",
                    },
                });

                if (response.ok) {
                    const li = document.getElementById(`request-${requestID}`); 
                    li.remove();
                    alert("Friend request accepted."); 
                } else {
                    alert("Error accepting friend request.");
                }
            } catch (error) {
                alert("An error occurred.");
            }
        }
    }

    async function rejectFriendRequest(requestID) {
        if (confirm("Are you sure you want to reject this friend request?")) {
            const endpointURL = `{% url 'users:reject_friend_request' requestID=99999 %}`.replace('99999', requestID);

            try {
                const response = await fetch(endpointURL, {
                    method: "POST",
                    headers: {
                        "X-CSRFToken": "{{ csrf_token }}",
                    },
                });

                if (response.ok) {
                    const li = document.getElementById(`request-${requestID}`); 
                    li.remove(); // Remove the list item from the page
                    alert("Friend request rejected.");
                } else {
                    alert("Error rejecting friend request.");
                }
            } catch (error) {
                alert("An error occurred.");
            }
        }
    }
</script>
{% endblock script %}

users/templates/users/friends.html
{% extends 'base.html' %}
{% block body %}
<div class="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
    <h1 class="text-3xl font-bold text-gray-800 mb-4">Your Friends</h1>

    <div class="w-full md:w-1/2">
        {% if friends %}
            <ul class="bg-white rounded-md shadow-md divide-y divide-gray-200">
                {% for friend in friends %}
                    <li class="px-6 py-4 flex items-center justify-between" id="friend-{{ friend.id }}"> 
                        <div class="flex items-center">
                            <img src="{{ friend.socialaccount_set.all.0.extra_data.picture }}" class="rounded-full w-8 h-8" alt="Profile Picture">
                            <div class="ml-4">
                                <a href="{% url 'users:profile' user_id=friend.id%}">
                                    <p class="text-lg font-medium text-gray-800">{{ friend.first_name }} {{ friend.last_name }}</p>
                                </a>
                            </div>
                        </div>
                        <button class="bg-red-500 hover:bg-red-700 text-white text-sm py-1 px-3 rounded focus:outline-none focus:shadow-outline" 
                                onclick="removeFriend({{ friend.id }})">
                            Remove
                        </button>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <div class="bg-white rounded-md shadow-md p-6 text-center">
                <p class="text-gray-700">You don't have any friends currently.</p>
            </div>
        {% endif %}
    </div>

    <div class="mt-8 w-full md:w-1/2">
        <h2 class="text-xl font-bold text-gray-800 mb-2">Send Friend Request</h2>
        <div class="flex">
            <input type="number" id="user_id_input" class="border rounded-md py-2 px-3 mr-2 w-full" placeholder="Enter User ID">
            <button id="send_request_btn" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-md focus:outline-none focus:shadow-outline">
                Send Request
            </button>
        </div>
        <div id="request_message" class="text-gray-700 mt-2"></div>
    </div>

    <div class="mt-4 w-full md:w-1/2 text-center"> 
        <a href="{% url 'users:received_friend_request' %}" class="text-blue-500 hover:underline">
            View Received Friend Requests
        </a>
    </div>
</div>
{% endblock body %}

{% block script %}
<script>
    const sendRequestBtn = document.getElementById('send_request_btn');
    const userIdInput = document.getElementById('user_id_input');
    const requestMessage = document.getElementById('request_message');

    sendRequestBtn.addEventListener('click', async () => {
        const userId = userIdInput.value;
        if (userId === "") {
            requestMessage.textContent = "Please enter a User ID.";
            return;
        }

        const endpointURL = `{% url 'users:friend_request' user_id=99999 %}`.replace('99999', userId);

        try {
            const response = await fetch(endpointURL, {
                method: "POST",
                headers: {
                    "X-CSRFToken": "{{ csrf_token }}",
                },
            });

            if (response.ok) {
                requestMessage.textContent = await response.text(); // Display the response message
            } else {
                requestMessage.textContent = "Error sending friend request.";
            }
        } catch (error) {
            requestMessage.textContent = "An error occurred.";
        }
    });
    async function removeFriend(friendID) {
        if (confirm("Are you sure you want to remove this friend?")) {
            const endpointURL = `{% url 'users:remove_friend' friendID=99999 %}`.replace('99999', friendID); 

            try {
                const response = await fetch(endpointURL, {
                    method: "POST",
                    headers: {
                        "X-CSRFToken": "{{ csrf_token }}",
                    },
                });

                if (response.ok) {
                    // Remove the friend's list item from the page
                    const li = document.getElementById(`friend-${friendID}`); 
                    li.remove(); 
                    alert("Friend removed successfully!"); 
                } else {
                    alert("Error removing friend.");
                }
            } catch (error) {
                alert("An error occurred.");
            }
        }
    }
</script>
{% endblock script %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% block body %}
<div class="container mx-auto flex flex-col items-center justify-center min-h-96 p-4">
    <div class="flex flex-col items-center text-center my-16">
        
        <img src="{{ profile_user.socialaccount_set.all.0.extra_data.picture }}" class="rounded-full w-32 h-32 mb-4" alt="Profile Picture">
        
        <h1 class="text-7xl text-gray-800">{{ profile_user.first_name }} {{ profile_user.last_name }}</h1>
        {% if user.id == profile_user.id %}
        <h1 class="text-xl text-gray-500">My User ID: {{ user.id }}</h1>
        {% endif %}
    </div>
    <div class="flex flex-col md:flex-row items-center justify-center space-x-8 md:space-x-16">
        <div class="flex flex-col items-start justify-start space-y-4">
            <h2 class="text-xl font-bold text-gray-800">Game Statistics</h2>
            <div class="border rounded-md p-4 shadow-md overflow-y-auto h-96">
                <p class="text-gray-700">Games Completed: {{profile.games_completed}}</p>
                <p class="text-gray-700">Subjects Completed:</p>
                <ul class="list-disc pl-6">
                    {% for subject, cnt in profile.subjects_completed.items %}
                        <li class="text-gray-700">{{subject}}: {{cnt}}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="flex flex-col items-start justify-start space-y-4 w-1/3">
            <h2 class="text-xl font-bold text-gray-800">Achievements</h2>
            <div class="border rounded-md p-4 shadow-md overflow-y-auto h-96">
                {% if achievements %}

                    <ul class="list-disc pl-6">
                        {% for achievement in achievements %}
                            <li class="text-gray-700 flex items-center"> 
                                <div class="flex flex-col"> 
                                <span class="font-bold text-indigo-600">{{ achievement.name }}</span>
                                <p class="text-sm text-gray-600">{{ achievement.description }}</p>  
                                </div>
                                {% if user.id == profile_user.id %}
                                <button 
                                    class="ml-4 bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded-md focus:outline-none focus:shadow-outline text-xs"
                                    data-achievement-id="{{ achievement.id }}"
                                    onclick="deleteAchievement(this)"
                                >
                                    Delete
                                </button>
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                <div class="bg-white rounded-md shadow-md p-6 text-center">
                    <p class="text-gray-700">You don't have any achievements currently.</p>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock body %}
{% block script %}
<script>
    async function deleteAchievement(button) {
        const achievementId = button.dataset.achievementId;
        const endpointURL = `{% url 'users:delete_achievement' %}?achievement_id=${achievementId}`; 

        if (confirm("Are you sure you want to delete this achievement? You can't revert this action.")) {
            try {
                const response = await fetch(endpointURL, {
                    method: "POST",
                    headers: {
                        "X-CSRFToken": "{{ csrf_token }}",
                    },
                });
                if (response.ok) {
                    button.closest("li").remove();
                    location.reload()
                } else {
                    console.error("Error deleting achievement:", response.status);
                    console.log(response);
                }
            } catch (error) {
                console.error("Error occurred:", error);
            }
        }
    }
</script>
{% endblock script %}