edugame/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('game/', include('game.urls')),
    path('users/', include('users.urls')),
    path('', include('home.urls')),
    path('accounts/', include('allauth.urls')),
]

game/urls.py
from django.urls import path, include
from . import views

app_name = 'game'

urlpatterns = [
    path('start/', views.start_game, name='start_game'),
    path('load/<int:game_id>/', views.load_game, name='load_game'),
    path('generate/<int:game_id>/', views.generate_questions, name='generate_questions'),
    path('play/<int:game_id>/', views.play_game, name='play_game'),
    path('end/<int:game_id>/', views.end_game, name='end_game'),
    path('list/', views.list_game, name="list"),
    path('delete/', views.delete_game, name="delete"),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('save_achievement/', views.save_achievement, name="save_achievement"),
    path('delete_achievement/', views.delete_achievement, name='delete_achievement'),
    path('friends/', views.list_friends, name="friends"),
    path('friends/add/<int:user_id>/', views.send_friend_request, name="friend_request"),
    path('friends/requests/', views.list_received_request, name="received_friend_request"),
    path('friends/accept/<int:requestID>/', views.accept_friend_request, name="accept_friend_request"),
    path('friends/reject/<int:requestID>/', views.reject_friend_request, name="reject_friend_request"),
    path('friends/remove/<int:friendID>/', views.remove_friend, name="remove_friend"),
]

templates/base.html
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EduGame</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="min-h-screen bg-gray-100">
    <header class="bg-purple-600 text-white sticky top-0 z-10">
        <section class="max-w-4xl mx-auto p-4 flex justify-between items-center">
            <a href="{% url 'index' %}" class="flex items-center">
                <span class="text-3xl font-medium mr-2">
                    🎓EDUGAME
                </span>
            </a>
            <div>
                <nav class="flex space-x-8 text-xl">
                    {% if not user.is_authenticated %}
                    <a href="{% provider_login_url 'google' %}" class="hover:underline">Sign In with Google</a>
                    {% else %}
                    <a href="{% url 'users:friends'%}" class="hover:underline">
                        <p class="text-xl">Friends</p>
                    </a>
                    <a href="{% url 'users:profile' user_id=user.id %}" class="hover:underline">
                        <p class="text-xl">Profile</p>
                    </a>
                    <a href="{% url 'account_logout' %}" class="hover:underline">Sign Out</a>
                    {% endif %}
                </nav>
            </div>
        </section>
    </header>
    {% block body %}
    {% endblock body %}
</body>
{% block script %}
{% endblock script %}
</html>